### Test login redirect
GET https://cst8919-lab2-g6cyfxcbbabadnas.canadacentral-01.azurewebsites.net/login

### Test callback with missing code (should trigger LOGIN_FAILURE log)
GET https://cst8919-lab2-g6cyfxcbbabadnas.canadacentral-01.azurewebsites.net/callback?code=invalidcode&state=fake

### Total login failures 13